nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  "@backstage/plugin-catalog-backend@*":
    dependencies:
      glob: "^13.0.0"

  "typescript-json-schema@*":
    dependencies:
      glob: "^13.0.0"

  "recursive-readdir@*":
    dependencies:
      minimatch: "^10.1.1"
